'''
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
'''


def sum_to_limit(limit=4000000):
    return sum(i for i in generate_to_limit(limit))


def generate_to_limit(limit):
    lower_even = 0
    higher_even = 2
    while (higher_even <= limit):
        yield higher_even
        higher_even, lower_even = next_pair(higher_even, lower_even)


def next_pair(higher_even, lower_even):
    '''Because math.'''
    return (4 * higher_even) + lower_even, higher_even


if __name__ == '__main__':
    print(sum_to_limit())  # => 4613732
